/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import logica.Importado;
import logica.Nacional;
import logica.Producto;

/**
 *
 * @author Tiago
 */
public class IngresoArticulo extends javax.swing.JFrame {

    /**
     * Creates new form IngresoArticulo
     */
    private Producto listaArticulos;

    public IngresoArticulo(Producto listaProducto) {
        listaArticulos = listaProducto;
        initComponents();
        this.setTitle("Ingresar Articulo");
        this.setLocationRelativeTo(null);
        btnGroupNacImp.add(checkBoxNacional);
        btnGroupNacImp.add(checkBoxImportado);
        panelNacional.setVisible(false);
        panelImportado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupNacImp = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        JTextFieldNombre = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jLabelUnidades = new javax.swing.JLabel();
        unidadesTexto = new javax.swing.JTextField();
        btnIngresarArticulo = new javax.swing.JButton();
        ingresoArticuloVolver = new javax.swing.JButton();
        checkBoxImportado = new javax.swing.JCheckBox();
        checkBoxNacional = new javax.swing.JCheckBox();
        panelImportado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        añoImportadoTexto = new javax.swing.JTextField();
        impuestoTexto = new javax.swing.JTextField();
        panelNacional = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        departamentoTexto = new javax.swing.JTextField();
        subsidioCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 500));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Gill Sans Nova Cond XBd", 0, 14)); // NOI18N
        jLabelTitulo.setText("INGRESE LAS CARACTERÍSTICAS DEL ARTÍCULO");

        jLabelNombre.setText("nombre:");

        JTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelCodigo.setText("código:");

        jLabelPrecio.setText("precio costo:");

        jLabelUnidades.setText("unidades disponibles:");

        btnIngresarArticulo.setText("Ingresar Artículo");
        btnIngresarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarArticuloActionPerformed(evt);
            }
        });

        ingresoArticuloVolver.setText("Volver");
        ingresoArticuloVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoArticuloVolverActionPerformed(evt);
            }
        });

        checkBoxImportado.setText("Importado");
        checkBoxImportado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxImportadoActionPerformed(evt);
            }
        });

        checkBoxNacional.setText("Nacional");
        checkBoxNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNacionalActionPerformed(evt);
            }
        });

        panelImportado.setBackground(new java.awt.Color(204, 255, 255));
        panelImportado.setPreferredSize(new java.awt.Dimension(188, 103));
        panelImportado.setVerifyInputWhenFocusTarget(false);

        jLabel6.setText("Año importado:");

        jLabel7.setText("Impuesto:");

        javax.swing.GroupLayout panelImportadoLayout = new javax.swing.GroupLayout(panelImportado);
        panelImportado.setLayout(panelImportadoLayout);
        panelImportadoLayout.setHorizontalGroup(
            panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImportadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(añoImportadoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(impuestoTexto))
                .addContainerGap())
        );
        panelImportadoLayout.setVerticalGroup(
            panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(añoImportadoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelImportadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(impuestoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        panelNacional.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setText("Departamento:");

        departamentoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoTextoActionPerformed(evt);
            }
        });

        subsidioCheckBox.setText("Subsidio");
        subsidioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsidioCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNacionalLayout = new javax.swing.GroupLayout(panelNacional);
        panelNacional.setLayout(panelNacionalLayout);
        panelNacionalLayout.setHorizontalGroup(
            panelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNacionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departamentoTexto)
                .addContainerGap())
            .addGroup(panelNacionalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(subsidioCheckBox)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelNacionalLayout.setVerticalGroup(
            panelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNacionalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(departamentoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(subsidioCheckBox)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUnidades)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unidadesTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCodigo)
                            .addComponent(JTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jTextFieldCost))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ingresoArticuloVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelImportado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(panelNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkBoxImportado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxNacional)
                        .addGap(84, 84, 84))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(JTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadesTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidades))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBoxImportado)
                    .addComponent(checkBoxNacional))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelImportado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarArticulo)
                    .addComponent(ingresoArticuloVolver))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarArticuloActionPerformed
        if (checkBoxNacional.isSelected()) {
            int codigo = Integer.parseInt(jTextFieldCodigo.getText());
            String nombre = JTextFieldNombre.getText();
            double precioCosto = Double.parseDouble(jTextFieldCost.getText());
            int unidades = Integer.parseInt(unidadesTexto.getText());
            String departamento = departamentoTexto.getText();
            if (subsidioCheckBox.isSelected()) {
                boolean subsidio = true;
                Nacional nuevoArticuloNacional = new Nacional(departamento, subsidio, codigo, nombre, precioCosto, unidades);
                listaArticulos.añadirArticulo(nuevoArticuloNacional);
            } else {

                boolean subsidio = false;
                Nacional nuevoArticuloNacional = new Nacional(departamento, subsidio, codigo, nombre, precioCosto, unidades);
                listaArticulos.añadirArticulo(nuevoArticuloNacional);
            }
        } else if (checkBoxImportado.isSelected()) {
            int codigo = Integer.parseInt(jTextFieldCodigo.getText());
            String nombre = JTextFieldNombre.getText();
            double precioCosto = Double.parseDouble(jTextFieldCost.getText());
            int unidades = Integer.parseInt(unidadesTexto.getText());
            int añoImportacion = Integer.parseInt(añoImportadoTexto.getText());
            double impuesto = Double.parseDouble(impuestoTexto.getText());
            Importado nuevoArticuloImportado = new Importado(añoImportacion, impuesto, codigo, nombre, precioCosto, unidades);
            listaArticulos.añadirArticulo(nuevoArticuloImportado);          
        }
       
    }//GEN-LAST:event_btnIngresarArticuloActionPerformed

    private void ingresoArticuloVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoArticuloVolverActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ingresoArticuloVolverActionPerformed

    private void checkBoxNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNacionalActionPerformed
        if (checkBoxNacional.isSelected()) {
            panelImportado.setVisible(false);
            panelNacional.setVisible(true);
        }
    }//GEN-LAST:event_checkBoxNacionalActionPerformed

    private void checkBoxImportadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxImportadoActionPerformed

        if (checkBoxImportado.isSelected()) {
            panelNacional.setVisible(false);
            panelImportado.setVisible(true);
        }
    }//GEN-LAST:event_checkBoxImportadoActionPerformed

    private void departamentoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoTextoActionPerformed

    private void subsidioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsidioCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subsidioCheckBoxActionPerformed

    private void JTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IngresoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IngresoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IngresoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IngresoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IngresoArticulo().setVisible(true);
//            }
//        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldNombre;
    private javax.swing.JTextField añoImportadoTexto;
    private javax.swing.ButtonGroup btnGroupNacImp;
    private javax.swing.JButton btnIngresarArticulo;
    private javax.swing.JCheckBox checkBoxImportado;
    private javax.swing.JCheckBox checkBoxNacional;
    private javax.swing.JTextField departamentoTexto;
    private javax.swing.JTextField impuestoTexto;
    private javax.swing.JButton ingresoArticuloVolver;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUnidades;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JPanel panelImportado;
    private javax.swing.JPanel panelNacional;
    private javax.swing.JCheckBox subsidioCheckBox;
    private javax.swing.JTextField unidadesTexto;
    // End of variables declaration//GEN-END:variables
}
